### ISSUE TITLE
Remove 'NMR spectral processing protocols' from view

### ISSUE THREAD

**Issue by elulrich** [uwbmrb/InstantDep#11]
Remove 'NMR spectral processing protocols' from left hand view default (dictionary issue)

**Comment by jonwedell** [comment]
@elulrich, this saveframe category still appears in the interface. Do we want to update the visibility of it in the xlschem_ann.csv, or should I add a rule to hide it to the overrides? When (if ever) should it be displayed?

**Comment by jonwedell** [comment]
Confirmed.
