### ISSUE TITLE
'General tensors' in default view but gone after data file upload

### ISSUE THREAD

**Issue by elulrich** [uwbmrb/InstantDep#12]
'General tensors' appears in left hand box when user first enters deposition system (dictionary issue). However, the prompt disappears after a data file is selected and uploaded.

As for all of the 'Remove' issues that were just submitted, these prompts/selections appear in the left hand box before any data files are uploaded.

**Comment by jonwedell** [comment]
This issue is fixed (and has been for a while) for all saveframes that shouldn't have showed up until the relevant data files were selected. The fix involved fixing some of the rules in `adit-man_over.csv` which will eventually need to get propagated to the production schema.
