### ISSUE TITLE
BMRBDep on Firefox

### ISSUE THREAD

**Issue by kcahya** [uwbmrb/InstantDep#20]
Got network error notification every time after each entries.

**Comment by jonwedell** [comment]
Resolved. For future reference, this issue was related to CORS and the differences between Firefox and Chrome in how it is implemented. On the server, to fix this, I changed:

```Header add Access-Control-Allow-Methods "*"```

to

```Header add Access-Control-Allow-Methods "GET, PUT, POST, DELETE, HEAD, OPTIONS"```
