### ISSUE TITLE
File type missing on BMRBDep

### ISSUE THREAD

**Issue by kcahya** [uwbmrb/InstantDep#21]
The file type "constraints" is missing in file type choices.

**Comment by jonwedell** [comment]
Do you recall which entry had an uploaded data file of type "constraints"? It would help me resolve this to be able to see it.

**Comment by kcahya** [comment]
It's entry 15000:
      4   noe_19f_42sq.tbl    'Constraints File'           .       .   15000   1
      5   hbonds.tbl          'Constraints File'           .       .   15000   1
      6   phi.tbl             'Constraints File'           .       .   15000   1
      7   psi.tbl             'Constraints File'           .       .   15000   1
      8   rotamers_40.tbl     'Constraints File'           .       .   15000   1

**Comment by elulrich** [comment]
Hi,

The constraints selection was available when ADIT-NMR was a one-stop 
deposition for coordinates, constraints, and all other data. It was 
turned off when the one-dep system went live. I believe.

Thanks,
Eldon

**Comment by jonwedell** [comment]
So we don't need the ability to capture constraints for BMRB-only depositions?

**Comment by dmaziuk** [comment]
I'm not sure constraints make any sense without the coordinates, I would expect if you have constraints, you're depositing a structure to OneDep.

**Comment by elulrich** [comment]
I believe that is correct for now unless things change in the future.
Eldon

**Comment by jonwedell** [comment]
Thanks, guys.
