### ISSUE TITLE
_Chem_comp.Image_file_name has issues

### ISSUE THREAD

**Issue by jonwedell** [uwbmrb/InstantDep#27]
This tag would allow you to select which image file you uploaded, but no image file type is defined in the standard file upload types dictionary. Therefore the tag has an empty enumeration list. I imagine ADIT had custom code for handling uploaded images. Need to discuss with Eldon best way to address this.

**Comment by dmaziuk** [comment]
IMO this tag should be taken out and shot: I believe it came from RCSB and their ligand processing pipeline at the time. This existed as a separate file upload box in ADIT-NMR at one point and I don't think anyone has ever uploaded an image to us. ADIT has no code AFAIK: the annotators are supposed to look at the file and do something.

For ligand processing, if we ever do it, we'll want a MOL/SDF or an ALATIS InChI string. Not an image. (Of course if you accept those, you can create the chem_comp automatically from them and not need to involve the annotator.)

Metabolomics entries right now have 3 images: 3D PNG, 2D "presentation" SVG, and a 2D SVG with all atom labels. they also have 23 "structure" files: a MOL and an SDF (apparently JMol can display SDF) -- but there's only one tag. So as of the latest batch, these all go into entry_information._Auxiliary_files

**Comment by jonwedell** [comment]
Thanks for the information! Would you suggest updating the dictionary to hide this tag? That would fix the issue from the perspective of the deposition system, and would make sense if it isn't being used anyways.

A did a [quick check](http://webapi.bmrb.wisc.edu/v2/search/get_all_values_for_tag/_Chem_comp.Image_file_name) just to verify, and it looks like somehow it did actually get filled for 12 entries.

**Comment by dmaziuk** [comment]
I was wrong: we still have a separate upload box for 
> Image (e.g. GIF, PNG) or definition (e.g. MOL, SDF) file describing the structure of a non-standard residue or ligand.

**Comment by jonwedell** [comment]
This was fixed by adding image file to the file types list in the API schema loader [here](https://github.com/uwbmrb/BMRB-API/commit/f17a39e57d76b0e23c1125646093f07c01187e29). During a future dictionary update, we need to add this new rule to the `adit_nmr_upload_tags.csv` and `adit_interface_dict.txt` files to prevent the need to manually insert it.

**Comment by jonwedell** [comment]
@elulrich - Can you set column 3 (associated saveframe) to `chem_comp` for `_Entry_interview.Image_file` in file `adit_nmr_upload_tags.csv`? Should be a quick fix.

**Comment by jonwedell** [comment]
Confirmed.
