### ISSUE TITLE
Should 'Software name' be 'Software label'

### ISSUE THREAD

**Issue by elulrich** [uwbmrb/InstantDep#3]
The prompt is 'Software name' in Software descriptions but in other sections the prompt is 'Sample label'. Should the software prompt be changed for consistency?

**Comment by jonwedell** [comment]
Yes, I think that change makes sense.

**Comment by jonwedell** [comment]
This is associated with #16 as in ADIT software label is created from software name.

**Comment by jonwedell** [comment]
Seeing this present, I start to wonder if name is clearer. Label makes sense for sample conditions, but when people are entering a software package, they are probably thinking about it's name rather than realizing that what they are entering, while actually the name, is also used as a label.

**Comment by jonwedell** [comment]
Confirmed.
