### ISSUE TITLE
For "text" boxes, attempt to auto-resize to match data already entered

### ISSUE THREAD

**Issue by jonwedell** [uwbmrb/InstantDep#32]
Polymer one letter code is a good example of such a tag.

**Comment by rsiegl** [comment]
I found that when you type anything into the "variable size" text boxes the size of the box becomes as small as it can become. Also if you type out a long enough text it expands the page so there is blank white space created to the side of the boxes. I will show you this and further explain it in person next time we are both in the office.

**Comment by jonwedell** [comment]
Closing as this was verified fixed.

**Comment by rsiegl** [comment]
This issue was fixed.
