### ISSUE TITLE
The natural source section does not give the option to input any information about the kingdom, genus, etc. 

### ISSUE THREAD

**Issue by jonwedell** [uwbmrb/InstantDep#37]
It also does not have the option to input any information about what the natural sources common name or scientific name or even NCBI code. It shows in ADIT. Need to determine if this is a dictionary or code issue.

**Comment by jonwedell** [comment]
Fixed in 5a26f7f. The problem was that there are loop-tag based conditional rules which I didn't realize existed. The code to handle those properly now exists.

@rsiegl - Please confirm.

**Comment by rsiegl** [comment]
I can confirm this is fixed.
