### ISSUE TITLE
Rules regarding yes/no values in chemical shift references have unexpected results for manditoriness of chemical shift reference data loop.

### ISSUE THREAD

**Issue by jonwedell** [uwbmrb/InstantDep#38]
The chemical shift reference data section tags become required whenever the user specifies "no" to whether or not they have data for certain types of shifts.

**Comment by jonwedell** [comment]
I can no longer reproduce this - it seems to be correct now. (I.e. "yes" selections add additional optional fields to the "reference" loop. @rsiegl - can you verify if it still behaves unexpectedly for you?

**Comment by rsiegl** [comment]
Upon going through an entry at this time, December 14th circa 4pm, I found that the chemical shift reference data section is not required when you have a form of yes selected for the shifts deposited. When all are no the section is required.

**Comment by jonwedell** [comment]
Confirmed, this is definitely still broken. ADIT apparently has some hard coded rules whereby it sometimes constructs the reference values automatically. This will need a good amount of work to fix.

Plus, the schema values seem wrong. The default for the reference fields is mandatory, and then if a "yes" value is present they are set to non-mandatory. I'm guessing the values from the schema never mattered because they were overwritten by whatever code in ADIT drives the autofilling of the values.

The relevant overrides rules:

Sf category | Tag category | Tag | Override view value | Conditional tag category | Conditional tag | Override value
-- | -- | -- | -- | -- | -- | --
chem_shift_reference | Chem_shift_ref | * | N | Chem_shift_reference | _Chem_shift_reference.Proton_shifts_flag | .*yes.*
chem_shift_reference | Chem_shift_ref | * | N | Chem_shift_reference | _Chem_shift_reference.Carbon_shifts_flag | .*yes.*
chem_shift_reference | Chem_shift_ref | * | N | Chem_shift_reference | _Chem_shift_reference.Nitrogen_shifts_flag | .*yes.*
chem_shift_reference | Chem_shift_ref | * | N | Chem_shift_reference | _Chem_shift_reference.Phosphorus_shifts_flag | .*yes.*
chem_shift_reference | Chem_shift_ref | * | N | Chem_shift_reference | _Chem_shift_reference.Other_shifts_flag | .*yes.*

**Comment by dmaziuk** [comment]
"yes with IUPAC referencing" is the option that triggers auto-fill-in. IIRC

**Comment by rsiegl** [comment]
I was just going through an entry and it appears that now the " 1H Chemical Shifts Deposited" field works now. When that field is no the reference data is not needed, but when it is either of the two yes values the reference data is required. Although based on what Dimitri said it sounds like the reference data is not required for "yes with IUPAC referencing". The other fields are still not working though.

**Comment by jonwedell** [comment]
I've updated the dictionary, and created custom code in d3cbe79 that should auto-fill the chem_shift_ref loop based on the values you enter in the chemical_shift_reference saveframe.

@rsiegl - Please confirm fix.

**Comment by jonwedell** [comment]
There was a bug in the indirect referencing value tag, fixed in 2da6190.

**Comment by jonwedell** [comment]
Reference loop auto-update logic improved in dee5324.

**Comment by jonwedell** [comment]
@rsiegl  - Thanks for the notification; that behavior was on purpose. I didn't want to erase the IUPAC values that had been entered if they are switching from IUPAC to non-IUPAC in order to update just one field. This matches the behavior of ADIT.

**Comment by jonwedell** [comment]
Also, I added the ability to show tags but disable them in order to truly force the loop to stay consistent with the saveframe in 8fca69e.
