### ISSUE TITLE
Add super group names to adit_cat_grp_o.csv file

### ISSUE THREAD

**Issue by jonwedell** [uwbmrb/InstantDep#41]
Currently the file `adit_cat_grp_o.csv` describes the super groups to use for the deposition interface, but it doesn't provide the readable names for them. I imagine ADIT has this hardcoded, because I can't track down the values that ADIT actually displays. 

I added my own hardcodings in 20a9f57 but I would like to remove them if we can add these values to  `adit_cat_grp_o.csv`. @elulrich - is this a change we can make?

**Comment by dmaziuk** [comment]
ADIT reads them from View-bmrb.cif that is constructed from several files. I believe ''adit_super_grp_o.cvs'' is the one you want to look at.

**Comment by jonwedell** [comment]
That is the file I'm reading, there currently aren't any "human friendly" super group names in it.

**Comment by jonwedell** [comment]
I don't believe any "human friendly" names even exist currently, as in ADIT the super-categories still display the underscores: `Experimental_descriptions` - for example.

**Comment by jonwedell** [comment]
> ADIT reads them from View-bmrb.cif that is constructed from several files. I believe ''adit_super_grp_o.cvs'' is the one you want to look at.

Ah, I misread this and didn't notice the difference between the `super` and `cat` in the filename you were talking about versus the one I had looked in. Apologies, thanks for pointing me in the correct direction right away.

**Comment by jonwedell** [comment]
Implemented in c741133.
