### ISSUE TITLE
Saveframe ordering is different in xlschem_ann and adit_cat_grp_o.csv

### ISSUE THREAD

**Issue by jonwedell** [uwbmrb/InstantDep#42]
InstantDep originally displayed the saveframes using the order tags from `xlschem_ann.csv`. `adit_cat_grp_o.csv` has a different ordering of the saveframes. This means that the "next category" and "previous category" buttons don't work as intended with the new supergroups, as they are still navigating using the native order of the NMR-STAR file rather than the order from `adit_cat_grp_o.csv`. @elulrich - should I use the ordering from the super groups file or the one from the main schema?

**Comment by dmaziuk** [comment]
saveframe ordering is ``min(dictionaryseq)`` for the tag category

**Comment by jonwedell** [comment]
That doesn't appear to be the case, at least for the navigation view. For example, in ADIT, it lists the saveframes in the following order:

1. Ligands, cofactors, etc.
2. Molecular entity
3. Molecular assembly

but according to dictionaryseq they should be in the following order:

1. Molecular assembly
2. Molecular entity
3. Ligands, cofactors, etc.

**Comment by dmaziuk** [comment]
In ADIT's left-side menu they come from ``adit_cat_grp_o``, if I remember correctly. In BMRB entries they're ordered as I said above.

**Comment by dmaziuk** [comment]
PS. If the question is why, filling in assembly components (entities and ligands) first would them let you construct the assembly from drop-down lists. When you're reading the STAR file, it makes sense to go top-down instead and see the assembly first. 

That was the argument I recall, ICBW, IIRC, and all that.

**Comment by jonwedell** [comment]
Order switched to that from `adit_cat_grp_o.csv` in commit 289cc06.
