### ISSUE TITLE
Display Non-mandatory tags button

### ISSUE THREAD

**Issue by rsiegl** [uwbmrb/InstantDep#44]
1. The display non-mandatory tags button is only visible in the side bar menu. Should that be visible on every page at the top by the next category buttons? 

2. When you click it and it hides the non-mandatory tags it changes the sizing of nearly everything. This is from when a non-mandatory tag is bigger than a mandatory tag. When the larger non-mandatory tag disappears it resizes whatever screen your on to the smaller tags that are mandatory. For example this happens on the side bar menu itself and moves the location of the non-mandatory/mandatory button to the line below.

3. If you are on a non-mandatory page and then click the on-mandatory/mandatory button to hide the non-mandatory fields, the page goes blank (as expected), but both of the next/previous category buttons become review deposition buttons. A next mandatory or previous mandatory category button could be useful here. The next category that is mandatory could just appear also rather than having the page become blank, but I am not sure how easy that would be to do.

**Comment by jonwedell** [comment]
1. This was an intentional change.
2. This should be fixed from some of the previous commit, and from 819cce7.
3. Fixed in d8ea5c9.

@rsiegl - Can you verify the fixes?

**Comment by rsiegl** [comment]
All fixes are confirmed.
