### ISSUE TITLE
All radio buttons are set to the same value

### ISSUE THREAD

**Issue by rsiegl** [uwbmrb/InstantDep#48]
On a page with multiple radio buttons for the yes/no selection, if you select one of the options it sets all other options on that page to the same value. For example on the Ligands, Cofactors, etc. page if you select yes for paramagnetic the aromatic option is put to yes. If you change the value for aromatic it also changes the paramagnetic selection. This seems to be happening on all pages with the radio buttons.

**Comment by jonwedell** [comment]
This must have been broken by the fix for issue #28.

**Comment by jonwedell** [comment]
Should be fixed in 92cc731 - already deployed on test server, please confirm.

**Comment by rsiegl** [comment]
That must have been it. I can confirm that it is fixed now.

**Comment by jonwedell** [comment]
Great, thanks.
