### ISSUE TITLE
Name vs Sf_framecode

### ISSUE THREAD

**Issue by rsiegl** [uwbmrb/InstantDep#49]
For both Molecular assembly and Ligands, cofactors, etc. the very first field, for name, always resets to chem_comp_1 or assembly_1 (the 1 is replaced by 2 if you duplicate or add a new section) regardless of what you type in. The help says that both of these fields point to the name section, but the fact that it keeps resetting to the above values makes me feel like it's pointing to Sf_framecode. It currently sets both the name and Sf_framecode values when you submit it. I am not sure if there is a reason for this or if perhaps these should be two different fields.

**Comment by jonwedell** [comment]
Should be fixed in 161759c.

**Comment by dmaziuk** [comment]
This has always been ugly in ADIT-NMR, it gets e.g. entity and software names out of the name tag, assembly is always "assembly", while sample etc. are "_1", "_2", and so on.

**Comment by jonwedell** [comment]
Indeed. Here is how I propose this is done with the new system:

- All new, schema-created entries have "_1" on the end of *all* saveframes. Standardize it.
- If the saveframe has a "Name" tag, it should be visible in the interface and sf_framecode should be hidden. Whenever the "Name" tag is populated, it is automatically sanitized (spaces and other illegal characters removed) and used to fill in the sf_framecode and saveframe name values. I suggested this in #51.

If existing code elsewhere in the pipeline works based on saveframe name and not saveframe category, the code the emits the final entry can re-name these special ones to the traditional values.

**Comment by rsiegl** [comment]
I can confirm that this was fixed. I also like that idea of having the Sf_framecode just be the sanitized version of the name if a name field is present.

**Comment by dmaziuk** [comment]
There is a regexp for saveframe names, and field length in the dictionary. Molecule names in particular rarely conform to the former and have been known to break the latter as well. Esp. names pulled from on-line sources.
