### ISSUE TITLE
Odd wording and 19F shifts

### ISSUE THREAD

**Issue by rsiegl** [uwbmrb/InstantDep#59]
Under the experimental source both of the following are required fields: "Type of vector used (if applicable)" and "Vector name (if applicable)". It seems odd that they are required, but also say if applicable.

I was also wondering if there was a reason why on the assigned chemical shifts page there is an option to put 19F shift error, but on the chemical shift references page there is no option to denote that 19F shifts have been deposited.

**Comment by jonwedell** [comment]
> Under the experimental source both of the following are required fields: "Type of vector used (if applicable)" and "Vector name (if applicable)". It seems odd that they are required, but also say if applicable.

Eldon plans to fix this in the dictionary, thanks.

> I was also wondering if there was a reason why on the assigned chemical shifts page there is an option to put 19F shift error, but on the chemical shift references page there is no option to denote that 19F shifts have been deposited.

There is such an option. You can specify "Other nuclei chemical shifts deposited" and then in the "Chemical shift reference data" loop there is a drop-down for "Atom type" where you can select "F".

**Comment by jonwedell** [comment]
The "if applicable" issues are fixed.
