### ISSUE TITLE
Change NMR experiments and samples to NMR experiments

### ISSUE THREAD

**Issue by elulrich** [uwbmrb/InstantDep#6]
In left had box change 'NMR experiments and samples' to 'NMR experiments' or 'NMR experiment descriptions'. Including 'samples' in this prompt can be confusing as users might be confused and think they have to enter sample information in two different places.

**Comment by dmaziuk** [comment]
Note that adit has a special-case code that lets people associate a sample with conditions and an experiment, and then that tuple pops up in drop-downs everywhere and experiment is needed. It gets cleaned up in post-processing somewhere.

**Comment by jonwedell** [comment]
Confirmed - changed to "NMR experimental descriptions".
