### ISSUE TITLE
Opening page difficult to read

### ISSUE THREAD

**Issue by elulrich** [uwbmrb/InstantDep#62]
In FireFox, the very opening page is difficult to read. In particular the rose shaded box, but also other boxes. Font is small. Bolding and larger fonts and for rose box make text contrast much more against background.

**Comment by jonwedell** [comment]
One comment: the color of the button to create the deposition will change in the future once I've finished creating the custom theme. Then it will match the light blue color used elsewhere.

**Comment by elulrich** [comment]
Looks good! A slight concern that depositors may not recognize that the first field is a pull down list especially if they have their browser set with a wide window.

**Comment by jonwedell** [comment]
I was a bit concerned about that as well, though I haven't found a great way to avoid that. One option is to start the "select deposition type" field unfilled, which forces them to chose an option. It would be impossible to miss this, as the deposition would not be allowed until a value was selected. The downside is that it requires one additional user-click before a deposition can be made.

**Comment by elulrich** [comment]
I like your idea of leaving this as a blank box the user has to make a selection. The only idea I had was to put some text under "Start a new deposition" that would indicate that there are three possible choices. But I could not think of brief enough comments that would maintain the clean look of the page.

**Comment by jonwedell** [comment]
I've made the change, and I think it's an improvement.

**Comment by elulrich** [comment]
I like it too!

**Comment by jonwedell** [comment]
Great!
