### ISSUE TITLE
Pre-fill entry authors middle initials

### ISSUE THREAD

**Issue by rsiegl** [uwbmrb/InstantDep#78]
When I did a pre-fill deposition by BMRB number, the deposition retained all of the entry author's first and last names, but did not retain the authors middle initials section. I am not sure if this is the same for the "upload NMR star file" option since that is currently down.

**Comment by jonwedell** [comment]
Should be fixed in https://github.com/uwbmrb/BMRB-API/commit/9a201a9817c16759b254de8a66e4fdb1f5200b61.

**Comment by rsiegl** [comment]
I can confirm this fix.
