### ISSUE TITLE
Pre-fill by uploading NMR star file

### ISSUE THREAD

**Issue by rsiegl** [uwbmrb/InstantDep#79]
When I tried to do this using BMRB entry 27721 it did not work, but using the BMRB number 27721 to pre-fill the deposition did work (Jon and I spoke about this in person also).

**Comment by jonwedell** [comment]
I think I understand what happened here. It was working when I tested it yesterday - for "external" entries. Uploading an internal one is what triggered the bug (specifically, and entry with the "entry_interview" saveframe). Should be fixed now.

**Comment by jonwedell** [comment]
Entry 27705 is not released, so it is the expected behavior that you will not be able to use its ID to start a new deposition.

The issue of uploaded files not working should also be resolved in https://github.com/uwbmrb/BMRB-API/commit/812d0a40b03cd42b9af936441c468fde6b54e837.

**Comment by rsiegl** [comment]
Yeah you're right, I can confirm that fix
