### ISSUE TITLE
Mandatory enumeration looks different in Safari

### ISSUE THREAD

**Issue by kumar-physics** [uwbmrb/InstantDep#85]

**Comment by kumar-physics** [comment]
<img width="1392" alt="screen shot 2019-02-01 at 10 06 06 am" src="https://user-images.githubusercontent.com/5636184/52134484-4a065180-2609-11e9-8900-3b85a3e8de19.png">

I have attached the screenshot

**Comment by jonwedell** [comment]
Confirmed on Kumaran's machine.
