### ISSUE TITLE
BMRB new testing system (bmrb 15000 as entry): Entry information>Contact Person

### ISSUE THREAD

**Issue by kcahya** [uwbmrb/InstantDep#86]
There is an additional row contact that cannot be deleted.

**Comment by rsiegl** [comment]
If my memory is correct, this is because we require two contact persons. That is why there is always two rows in this section.

**Comment by jonwedell** [comment]
Richard is correct, the interface is designed to require two contact people. That increases the odds that we'll always be able to contact at least one of them.
